### Math operation on Tensors
Thanks to [this](https://probability.dmi.unibas.ch/belius/teaching/intro_to_dl/4/1.html).

In [17]:
import torch
import numpy as np

# Basic operation
torch.normal(torch.zeros(5,5), torch.ones(5,5)) # Tensor.normal(means=0, std=1) <- Create tensor with
                                                                                     # random normal values.
                                                                                     # Means and std devs given
                                                                                     # as tensor

tensor([[-1.2733, -2.1828, -0.7823, -2.0865, -0.4526],
        [-0.2728,  0.8242, -0.2127,  1.4759,  0.1774],
        [-0.1577,  0.6758,  0.0538,  0.1331, -1.1212],
        [ 1.2139, -2.3406, -0.2546, -1.1089,  0.2498],
        [ 0.1836, -1.3481, -0.4450, -0.2822,  0.0686]])

#### Tensor creation

In [4]:
t = torch.Tensor(3,2)             # torch.Tensor(size) <- Create tensor of certain size
t = torch.zeros(3,2)              # torch.zeros(size)  <- Create tensor of certain size filled with zeros
t = torch.ones(3,2)               # torch.zeros(size)  <- Create tensor of certain size filled with ones
t = torch.Tensor( [[3,2],[1,0]] ) # torch.Tensor(sequence) <- Create tensor with certain entries
t = torch.eye(3)                  # torch.eye(n) <- Create identity matrix 
t = torch.from_numpy( np.array( [1,2,3] )) # torch.from_numpy(ndarray) <- Create PyTorch tensor from numpy array

t = torch.bernoulli(torch.ones(5,5)*0.3)   # torch.bernoulli(t)  <- Create tensor of same size as t with
                                                                  # Bernoulli RV in entries with p in corresponding    


#### Tensor filling

In [9]:
t = torch.Tensor(3,2)             # torch.Tensor(size) <- Create tensor of certain size
t = torch.zeros(3,2)              # torch.zeros(size)  <- Create tensor of certain size filled with zeros
t = torch.ones(3,2)               # torch.zeros(size)  <- Create tensor of certain size filled with ones
t = torch.Tensor( [[3,2],[1,0]] ) # torch.Tensor(sequence) <- Create tensor with certain entries
t = torch.eye(3)                  # torch.eye(n) <- Create identity matrix 
t = torch.from_numpy( np.array( [1,2,3] )) # torch.from_numpy(ndarray) <- Create PyTorch tensor from numpy array
t = torch.normal(torch.zeros(5,5), torch.ones(5,5)) # Tensor.normal(means=0, std=1) <- Create tensor with
                                                                                     # random normal values.
                                                                                     # Means and std devs given
                                                                                     # as tensor
t = torch.bernoulli(torch.ones(5,5)*0.3)   # torch.bernoulli(t)  <- Create tensor of same size as t with
                                                                  # Bernoulli RV in entries with p in corresponding    


#### Pointwise Math

In [10]:
t = torch.Tensor(5, 5)
t.normal_() ### in place operation

torch.abs(t)        # torch.abs(input, out=None) <- Absolute value entrywise
t.abs_()            # Tensor.abs_()              <- Absolute value in place 
torch.add(t, 2.0)   # torch.add(input, value, out=None)  <- Add scalar to each entry
t.add_(2.0)         # Tensor.add_(value)                 <- Add in place
torch.cos(t)        # t = torch.cos(input, out=None) <- Compute cos of entries
t.cos_()            # Tensor.cos_() <- Cos in place
torch.sigmoid(t)    # t = torch.sigmoid(input, out=None)   <- Compute sigmoid in place
t.sigmoid_()        # Tensor.sigmoid_() <- Simgoid in place
# (+ many others)

tensor([[0.2837, 0.2744, 0.3010, 0.3493, 0.3887],
        [0.3797, 0.2840, 0.3745, 0.2691, 0.3297],
        [0.3235, 0.3296, 0.2708, 0.3173, 0.3383],
        [0.2899, 0.2705, 0.6740, 0.2717, 0.2701],
        [0.2906, 0.2692, 0.3217, 0.3557, 0.2987]])

#### Math Reduction

In [12]:
t = torch.Tensor( 3,4 )
t.normal_()

t.sum()     # Tensor.sum( dim=-1 ) <- Compute sum
t.sum(0)    # Tensor.sum( 0 )         <- Compute sum over dimension 0
t.sum(1)    # Tensor.sum( 1 )         <- Compute sum over dimension 1
t.norm()    # Tensor.norm( p=2 ) <- Compute p-norm
t.mean()    # Tensor.mean() <- Compute mean
t.std()     # Tensor.std() <- Compute empirical standard deviation

tensor(0.7179)

#### Linear Algebra

In [14]:
t = torch.Tensor( 3,3 )
t.normal_()

torch.eig(t)                 # torch.eig(a, eigenvectors=False, out=None) <- Compute eigenvalues
torch.eig(t, True)           # Also compute eigenvectors
torch.inverse(t)             # torch.inverse(input, out=None) <- Compute inverse of matrix
torch.mm( t, t )             # torch.mm(mat1, mat2, out=None) <- Multiply matrices
torch.mv( t, torch.ones(3) ) # torch.mv(mat, vec, out=None)   <- Multiply matrix by vector

tensor([ 0.0914, -0.3382, -1.3096])

#### Operations on dimensions, slicing

In [15]:
t = torch.Tensor( 2, 4 )
t.normal_()

t.t()                 # Tensor.transpose() <- The transpose of t
t2 = t.view(2,2,2)    # Tensor.view(dim1, dim2, ..., dimn)  <- Convert a tensor of one shape to another
                      # (sizes must be compatible)
t2[0,0,0]=10.0        # Tensor.view creates a view on the same underlying data, so changing the view changes the
                      # original tensor.
# Now t[0,0] equals 10.0


t.view( 2, 4, 1 ).expand( 2, 4, 3 )   # Tensor.expand( dim1, dim2, dim3, ... ) 
                                      # ^ Create a view where copties of the tensor are stacked togehter,
                                      # in the dimensions the size of the tensor is 1.

t.narrow( 1, 1, 2 ) # Tensor.narrow( dim, start_idx_, length)
                    # ^ Create a view which contains a slice of the tensor, where
                    # only indices start_idx, start_idx+1,..., start_idx+length-1
                    # are kept from the dimension dim

tensor([[-1.2908, -0.7452],
        [-0.8651, -0.1754]])