#### Let's understand and twist the weight initialization in PyTorch

In [2]:
import torch
import numpy as np
from torch import nn

In [31]:
a = torch.Tensor([[4,5], [8,6]])
print(a)
print(a[0])
list(a.chunk(3,1))
a.chunk(2,0)

# help(torch.chunk)

tensor([[4., 5.],
        [8., 6.]])
tensor([4., 5.])


(tensor([[4., 5.]]), tensor([[8., 6.]]))

In [7]:
help(nn.InstanceNorm2d)

Help on class InstanceNorm2d in module torch.nn.modules.instancenorm:

class InstanceNorm2d(_InstanceNorm)
 |  InstanceNorm2d(num_features, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
 |  
 |  Applies Instance Normalization over a 4D input (a mini-batch of 2D inputs
 |  with additional channel dimension) as described in the paper
 |  `Instance Normalization: The Missing Ingredient for Fast Stylization`_ .
 |  
 |  .. math::
 |  
 |      y = \frac{x - \mathrm{E}[x]}{ \sqrt{\mathrm{Var}[x] + \epsilon}} * \gamma + \beta
 |  
 |  The mean and standard-deviation are calculated per-dimension separately
 |  for each object in a mini-batch. :math:`\gamma` and :math:`\beta` are learnable parameter vectors
 |  of size `C` (where `C` is the input size) if :attr:`affine` is ``True``.
 |  
 |  By default, this layer uses instance statistics computed from input data in
 |  both training and evaluation modes.
 |  
 |  If :attr:`track_running_stats` is set to ``True``, during tra

In [16]:
m = nn.InstanceNorm2d(1)
a = torch.randn(1,1,1,2)
print(m(a))
print(a)


tensor([[[[ 0.9975, -0.9975]]]])
tensor([[[[-0.0462, -0.1355]]]])
